### ISSUE TITLE
connect dies on timeout error

### ISSUE THREAD

**Issue by mcandre** [1ambda/docker-kafka-connect#1]
# Summary

I'm trying to spin up a kafka connect stack and redis, as I learn how to use kafka connect. However, when I try to spin up kafka connect and friends with docker-compose, the stack quickly dies.

When this happens, the next `docker-compose up` fails with an error about kafka already being up on its respective port, so I have to `docker-compose rm -f` to work around that.
# docker-compose.yml

```
zk:
  image: 31z4/zookeeper:3.4.8

kafka:
  image: ches/kafka
  links:
   - zk
  environment:
    KAFKA_BROKER_ID: 0
    KAFKA_ADVERTISED_HOST_NAME: kafka
    KAFKA_ADVERTISED_PORT: 9092
    ZOOKEEPER_CONNECTION_STRING: zk:2181
    ZOOKEEPER_CHROOT: /broker-0

connect:
  image: 1ambda/kafka-connect
  links:
   - kafka
  ports:
   - "8083:8083"
  environment:
   CONNECT_BOOTSTRAP_SERVERS: kafka:9092

redis:
  image: redis:3.2.1
  ports:
   - "6379:6379"
```
# Trace

```
$ docker-compose rm -f
$ docker-compose up
...
connect_1 | [2016-07-15 15:43:46,120] INFO jetty-9.2.15.v20160210 (org.eclipse.jetty.server.Server:327)
kafka_1   | [2016-07-15 15:43:46,138] INFO [Socket Server on Broker 0], Started 1 acceptor threads (kafka.network.SocketServer)
kafka_1   | [2016-07-15 15:43:46,212] INFO [ExpirationReaper-0], Starting  (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
kafka_1   | [2016-07-15 15:43:46,216] INFO [ExpirationReaper-0], Starting  (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
kafka_1   | [2016-07-15 15:43:46,350] INFO Creating /controller (is it secure? false) (kafka.utils.ZKCheckedEphemeral)
kafka_1   | [2016-07-15 15:43:46,368] INFO Result of znode creation is: OK (kafka.utils.ZKCheckedEphemeral)
kafka_1   | [2016-07-15 15:43:46,383] INFO 0 successfully elected as leader (kafka.server.ZookeeperLeaderElector)
zk_1      | 2016-07-15 15:43:46,398 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@651] - Got user-level KeeperException when processing sessionid:0x155ef3a4c260001 type:setData cxid:0x20 zxid:0x15 txntype:-1 reqpath:n/a Error Path:/broker-0/controller_epoch Error:KeeperErrorCode = NoNode for /broker-0/controller_epoch
zk_1      | 2016-07-15 15:43:46,606 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@651] - Got user-level KeeperException when processing sessionid:0x155ef3a4c260001 type:delete cxid:0x2f zxid:0x17 txntype:-1 reqpath:n/a Error Path:/broker-0/admin/preferred_replica_election Error:KeeperErrorCode = NoNode for /broker-0/admin/preferred_replica_election
kafka_1   | [2016-07-15 15:43:46,656] INFO [ExpirationReaper-0], Starting  (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
kafka_1   | [2016-07-15 15:43:46,661] INFO [ExpirationReaper-0], Starting  (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
kafka_1   | [2016-07-15 15:43:46,736] INFO [GroupCoordinator 0]: Starting up. (kafka.coordinator.GroupCoordinator)
kafka_1   | [2016-07-15 15:43:46,756] INFO [GroupCoordinator 0]: Startup complete. (kafka.coordinator.GroupCoordinator)
kafka_1   | [2016-07-15 15:43:46,792] INFO [Group Metadata Manager on Broker 0]: Removed 0 expired offsets in 49 milliseconds. (kafka.coordinator.GroupMetadataManager)
kafka_1   | [2016-07-15 15:43:46,868] INFO [ThrottledRequestReaper-Produce], Starting  (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
kafka_1   | [2016-07-15 15:43:46,874] INFO [ThrottledRequestReaper-Fetch], Starting  (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
kafka_1   | [2016-07-15 15:43:46,938] INFO Will not load MX4J, mx4j-tools.jar is not in the classpath (kafka.utils.Mx4jLoader$)
kafka_1   | [2016-07-15 15:43:47,029] INFO Creating /brokers/ids/0 (is it secure? false) (kafka.utils.ZKCheckedEphemeral)
zk_1      | 2016-07-15 15:43:47,072 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@651] - Got user-level KeeperException when processing sessionid:0x155ef3a4c260001 type:create cxid:0x36 zxid:0x18 txntype:-1 reqpath:n/a Error Path:/broker-0/brokers Error:KeeperErrorCode = NodeExists for /broker-0/brokers
zk_1      | 2016-07-15 15:43:47,076 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@651] - Got user-level KeeperException when processing sessionid:0x155ef3a4c260001 type:create cxid:0x37 zxid:0x19 txntype:-1 reqpath:n/a Error Path:/broker-0/brokers/ids Error:KeeperErrorCode = NodeExists for /broker-0/brokers/ids
kafka_1   | [2016-07-15 15:43:47,087] INFO Result of znode creation is: OK (kafka.utils.ZKCheckedEphemeral)
kafka_1   | [2016-07-15 15:43:47,090] INFO Registered broker 0 at path /brokers/ids/0 with addresses: PLAINTEXT -> EndPoint(kafka,9092,PLAINTEXT) (kafka.utils.ZkUtils)
kafka_1   | [2016-07-15 15:43:47,098] WARN No meta.properties file under dir /data/meta.properties (kafka.server.BrokerMetadataCheckpoint)
kafka_1   | [2016-07-15 15:43:47,200] INFO New leader is 0 (kafka.server.ZookeeperLeaderElector$LeaderChangeListener)
kafka_1   | [2016-07-15 15:43:47,229] INFO Kafka version : 0.10.0.0 (org.apache.kafka.common.utils.AppInfoParser)
kafka_1   | [2016-07-15 15:43:47,250] INFO Kafka commitId : b8642491e78c5a13 (org.apache.kafka.common.utils.AppInfoParser)
kafka_1   | [2016-07-15 15:43:47,256] INFO [Kafka Server 0], started (kafka.server.KafkaServer)
zk_1      | 2016-07-15 15:43:47,678 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@651] - Got user-level KeeperException when processing sessionid:0x155ef3a4c260001 type:setData cxid:0x3f zxid:0x1b txntype:-1 reqpath:n/a Error Path:/broker-0/config/topics/connect-offsets Error:KeeperErrorCode = NoNode for /broker-0/config/topics/connect-offsets
zk_1      | 2016-07-15 15:43:47,684 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@651] - Got user-level KeeperException when processing sessionid:0x155ef3a4c260001 type:create cxid:0x40 zxid:0x1c txntype:-1 reqpath:n/a Error Path:/broker-0/config/topics Error:KeeperErrorCode = NodeExists for /broker-0/config/topics
kafka_1   | [2016-07-15 15:43:47,707] INFO Topic creation {"version":1,"partitions":{"0":[0]}} (kafka.admin.AdminUtils$)
kafka_1   | [2016-07-15 15:43:47,724] INFO [KafkaApi-0] Auto creation of topic connect-offsets with 1 partitions and replication factor 1 is successful (kafka.server.KafkaApis)
zk_1      | 2016-07-15 15:43:47,851 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@651] - Got user-level KeeperException when processing sessionid:0x155ef3a4c260001 type:create cxid:0x48 zxid:0x1f txntype:-1 reqpath:n/a Error Path:/broker-0/brokers/topics/connect-offsets/partitions/0 Error:KeeperErrorCode = NoNode for /broker-0/brokers/topics/connect-offsets/partitions/0
zk_1      | 2016-07-15 15:43:47,857 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@651] - Got user-level KeeperException when processing sessionid:0x155ef3a4c260001 type:create cxid:0x49 zxid:0x20 txntype:-1 reqpath:n/a Error Path:/broker-0/brokers/topics/connect-offsets/partitions Error:KeeperErrorCode = NoNode for /broker-0/brokers/topics/connect-offsets/partitions
connect_1 | Jul 15, 2016 3:43:48 PM org.glassfish.jersey.internal.Errors logErrors
connect_1 | WARNING: The following warnings have been detected: WARNING: The (sub)resource method listConnectors in org.apache.kafka.connect.runtime.rest.resources.ConnectorsResource contains empty path annotation.
connect_1 | WARNING: The (sub)resource method createConnector in org.apache.kafka.connect.runtime.rest.resources.ConnectorsResource contains empty path annotation.
connect_1 | WARNING: The (sub)resource method listConnectorPlugins in org.apache.kafka.connect.runtime.rest.resources.ConnectorPluginsResource contains empty path annotation.
connect_1 | WARNING: The (sub)resource method serverInfo in org.apache.kafka.connect.runtime.rest.resources.RootResource contains empty path annotation.
connect_1 | 
connect_1 | [2016-07-15 15:43:48,427] INFO Started o.e.j.s.ServletContextHandler@68fa0ba8{/,null,AVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler:744)
connect_1 | [2016-07-15 15:43:48,508] INFO Started ServerConnector@5c58f095{HTTP/1.1}{0.0.0.0:8083} (org.eclipse.jetty.server.ServerConnector:266)
connect_1 | [2016-07-15 15:43:48,511] INFO Started @5825ms (org.eclipse.jetty.server.Server:379)
connect_1 | [2016-07-15 15:43:48,512] INFO REST server listening at http://172.17.0.5:8083/, advertising URL http://172.17.0.5:8083/ (org.apache.kafka.connect.runtime.rest.RestServer:150)
connect_1 | [2016-07-15 15:43:48,513] INFO Kafka Connect started (org.apache.kafka.connect.runtime.Connect:58)
connect_1 | [2016-07-15 15:44:04,459] INFO 192.168.99.1 - - [15/Jul/2016:15:44:04 +0000] "GET / HTTP/1.1" 200 50  260 (org.apache.kafka.connect.runtime.rest.RestServer:60)
connect_1 | [2016-07-15 15:44:08,257] INFO 192.168.99.1 - - [15/Jul/2016:15:44:08 +0000] "GET /Connectors HTTP/1.1" 404 288  6 (org.apache.kafka.connect.runtime.rest.RestServer:60)
connect_1 | [2016-07-15 15:44:10,900] INFO 192.168.99.1 - - [15/Jul/2016:15:44:10 +0000] "GET /Connector HTTP/1.1" 404 287  2 (org.apache.kafka.connect.runtime.rest.RestServer:60)
connect_1 | [2016-07-15 15:44:25,941] ERROR Uncaught exception in herder work thread, exiting:  (org.apache.kafka.connect.runtime.distributed.DistributedHerder:183)
connect_1 | org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata
connect_1 | [2016-07-15 15:44:25,946] INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect:68)
connect_1 | [2016-07-15 15:44:25,946] INFO Stopping REST server (org.apache.kafka.connect.runtime.rest.RestServer:154)
connect_1 | [2016-07-15 15:45:25,968] INFO Stopped ServerConnector@5c58f095{HTTP/1.1}{0.0.0.0:8083} (org.eclipse.jetty.server.ServerConnector:306)
connect_1 | [2016-07-15 15:45:25,995] INFO Stopped o.e.j.s.ServletContextHandler@68fa0ba8{/,null,UNAVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler:865)
connect_1 | [2016-07-15 15:45:49,395] WARN  (org.eclipse.jetty.servlet.ServletHandler:620)
connect_1 | javax.servlet.ServletException: A MultiException has 1 exceptions.  They are:
connect_1 | 1. java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_0,1,844112759) has been shut down
connect_1 | 
connect_1 |     at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:489)
connect_1 |     at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
connect_1 |     at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
connect_1 |     at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
connect_1 |     at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
connect_1 |     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
connect_1 |     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
connect_1 |     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
connect_1 |     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
connect_1 |     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
connect_1 |     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
connect_1 |     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
connect_1 |     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
connect_1 |     at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
connect_1 |     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
connect_1 |     at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159)
connect_1 |     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
connect_1 |     at org.eclipse.jetty.server.Server.handle(Server.java:499)
connect_1 |     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
connect_1 |     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
connect_1 |     at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
connect_1 |     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
connect_1 |     at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
connect_1 |     at java.lang.Thread.run(Thread.java:745)
connect_1 | Caused by: A MultiException has 1 exceptions.  They are:
connect_1 | 1. java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_0,1,844112759) has been shut down
connect_1 | 
connect_1 |     at org.jvnet.hk2.internal.FactoryCreator.getFactoryHandle(FactoryCreator.java:106)
connect_1 |     at org.jvnet.hk2.internal.FactoryCreator.dispose(FactoryCreator.java:173)
connect_1 |     at org.jvnet.hk2.internal.SystemDescriptor.dispose(SystemDescriptor.java:526)
connect_1 |     at org.glassfish.jersey.process.internal.RequestScope$Instance.remove(RequestScope.java:532)
connect_1 |     at org.glassfish.jersey.process.internal.RequestScope$Instance.release(RequestScope.java:549)
connect_1 |     at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:319)
connect_1 |     at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
connect_1 |     at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
connect_1 |     at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
connect_1 |     ... 23 more
connect_1 | Caused by: java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_0,1,844112759) has been shut down
connect_1 |     at org.jvnet.hk2.internal.ServiceLocatorImpl.checkState(ServiceLocatorImpl.java:2288)
connect_1 |     at org.jvnet.hk2.internal.ServiceLocatorImpl.getServiceHandleImpl(ServiceLocatorImpl.java:629)
connect_1 |     at org.jvnet.hk2.internal.ServiceLocatorImpl.getServiceHandle(ServiceLocatorImpl.java:622)
connect_1 |     at org.jvnet.hk2.internal.ServiceLocatorImpl.getServiceHandle(ServiceLocatorImpl.java:640)
connect_1 |     at org.jvnet.hk2.internal.FactoryCreator.getFactoryHandle(FactoryCreator.java:103)
connect_1 |     ... 31 more
connect_1 | [2016-07-15 15:45:49,407] INFO 192.168.99.1 - - [1468597459370] "GET /connectors HTTP/1.1" 500 294  90037 (org.apache.kafka.connect.runtime.rest.RestServer:60)
connect_1 | [2016-07-15 15:45:49,407] WARN /connectors (org.eclipse.jetty.server.HttpChannel:396)
connect_1 | javax.servlet.ServletException: javax.servlet.ServletException: A MultiException has 1 exceptions.  They are:
connect_1 | 1. java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_0,1,844112759) has been shut down
connect_1 | 
connect_1 |     at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:130)
connect_1 |     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
connect_1 |     at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159)
connect_1 |     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
connect_1 |     at org.eclipse.jetty.server.Server.handle(Server.java:499)
connect_1 |     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
connect_1 |     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
connect_1 |     at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
connect_1 |     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
connect_1 |     at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
connect_1 |     at java.lang.Thread.run(Thread.java:745)
connect_1 | Caused by: javax.servlet.ServletException: A MultiException has 1 exceptions.  They are:
connect_1 | 1. java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_0,1,844112759) has been shut down
connect_1 | 
connect_1 |     at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:489)
connect_1 |     at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
connect_1 |     at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
connect_1 |     at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
connect_1 |     at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
connect_1 |     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
connect_1 |     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
connect_1 |     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
connect_1 |     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
connect_1 |     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
connect_1 |     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
connect_1 |     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
connect_1 |     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
connect_1 |     at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
connect_1 |     ... 10 more
connect_1 | Caused by: A MultiException has 1 exceptions.  They are:
connect_1 | 1. java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_0,1,844112759) has been shut down
connect_1 | 
connect_1 |     at org.jvnet.hk2.internal.FactoryCreator.getFactoryHandle(FactoryCreator.java:106)
connect_1 |     at org.jvnet.hk2.internal.FactoryCreator.dispose(FactoryCreator.java:173)
connect_1 |     at org.jvnet.hk2.internal.SystemDescriptor.dispose(SystemDescriptor.java:526)
connect_1 |     at org.glassfish.jersey.process.internal.RequestScope$Instance.remove(RequestScope.java:532)
connect_1 |     at org.glassfish.jersey.process.internal.RequestScope$Instance.release(RequestScope.java:549)
connect_1 |     at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:319)
connect_1 |     at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
connect_1 |     at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
connect_1 |     at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
connect_1 |     ... 23 more
connect_1 | Caused by: java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_0,1,844112759) has been shut down
connect_1 |     at org.jvnet.hk2.internal.ServiceLocatorImpl.checkState(ServiceLocatorImpl.java:2288)
connect_1 |     at org.jvnet.hk2.internal.ServiceLocatorImpl.getServiceHandleImpl(ServiceLocatorImpl.java:629)
connect_1 |     at org.jvnet.hk2.internal.ServiceLocatorImpl.getServiceHandle(ServiceLocatorImpl.java:622)
connect_1 |     at org.jvnet.hk2.internal.ServiceLocatorImpl.getServiceHandle(ServiceLocatorImpl.java:640)
connect_1 |     at org.jvnet.hk2.internal.FactoryCreator.getFactoryHandle(FactoryCreator.java:103)
connect_1 |     ... 31 more
connect_1 | [2016-07-15 15:45:49,415] WARN Could not send response error 500: javax.servlet.ServletException: javax.servlet.ServletException: A MultiException has 1 exceptions.  They are:
connect_1 | 1. java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_0,1,844112759) has been shut down
connect_1 |  (org.eclipse.jetty.server.HttpChannel:482)
connect_1 | Exception in thread "Thread-1" java.lang.IllegalStateException: !STOPPED
connect_1 |     at org.eclipse.jetty.server.handler.HandlerWrapper.destroy(HandlerWrapper.java:131)
connect_1 |     at org.apache.kafka.connect.runtime.rest.RestServer.stop(RestServer.java:162)
connect_1 |     at org.apache.kafka.connect.runtime.Connect.stop(Connect.java:70)
connect_1 |     at org.apache.kafka.connect.runtime.Connect$ShutdownHook.run(Connect.java:93)
connect_1 | [2016-07-15 15:45:49,427] WARN FAILED org.eclipse.jetty.server.Server@22232f38: java.util.concurrent.TimeoutException (org.eclipse.jetty.util.component.AbstractLifeCycle:212)
connect_1 | java.util.concurrent.TimeoutException
connect_1 |     at org.eclipse.jetty.util.FutureCallback.get(FutureCallback.java:128)
connect_1 |     at org.eclipse.jetty.util.FutureCallback.get(FutureCallback.java:30)
connect_1 |     at org.eclipse.jetty.server.Server.doStop(Server.java:426)
connect_1 |     at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
connect_1 |     at org.apache.kafka.connect.runtime.rest.RestServer.stop(RestServer.java:157)
connect_1 |     at org.apache.kafka.connect.runtime.Connect.stop(Connect.java:70)
connect_1 |     at org.apache.kafka.connect.runtime.Connect$ShutdownHook.run(Connect.java:93)
hellokafkaconnect_connect_1 exited with code 0
Gracefully stopping... (press Ctrl+C again to force)
Stopping hellokafkaconnect_kafka_1... done
Stopping hellokafkaconnect_redis_1... done
Stopping hellokafkaconnect_zk_1... done
```
# System
- docker-machine 0.4.1 via Docker Toolbox
- Mac OS X 10.11.5 El Capitan

**Comment by 1ambda** [comment]
I will investigate it. Could you paste your 'docker ps' result? (after running docker compose up)

**Comment by 1ambda** [comment]
It seems that connect fails to fetch metadata from 0 broker even if the broker is already running. I think ZK and brokers are not wokring propery. Could you change ZK_CH_ROOT and run docker compose up again? (or remove stopped containers with docker rm `docker ps --no-trunc -aq`

**Comment by mcandre** [comment]
Not sure what I would change `ZK_CH_ROOT` _to_.

I ran `docker-compose rm -f && docker-compose up` and get the same error about missing kafka topic metadata.
- Could this be an issue with lag? In other words, maybe the connect container start script should wait a few seconds for the broker container to finish starting?
- Does Kafka Connect fail if Kafka has no topics? Could we modify the connect container start script to ensure a dummy topic is created before connect starts?

**Comment by mcandre** [comment]
Updated VirtualBox to v5.1, DockerToolbox to v1.11.2, and now 1ambda/docker-kafka-connect `docker-compose up` works on my machine!

**Comment by 1ambda** [comment]
Nice 👍
